version: 0.2

env:
  variables:
    ANDROID_HOME: "/root/android-sdk"
    PATH: "/root/android-sdk/cmdline-tools/latest/bin:/root/android-sdk/platform-tools:/root/android-sdk/build-tools/34.0.0:$PATH"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."
      - mkdir -p $ANDROID_HOME
      - cd $ANDROID_HOME
      - curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
      - unzip sdk-tools.zip -d cmdline-tools
      - mkdir -p cmdline-tools/latest
      - mv cmdline-tools/cmdline-tools/* cmdline-tools/latest/
      - yes | sdkmanager --licenses
      - yes | sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
      - cd $CODEBUILD_SRC_DIR
  build:
    commands:
      - echo "Starting Gradle build..."
      - chmod +x gradlew
      - ./gradlew assembleDebug

artifacts:
  files:
    - app/build/outputs/apk/debug/app-debug.apk
  discard-paths: yes
  base-directory: app/build/outputs/apk/debug
